### PR TITLE
Dark Mode Support + Shorter Code

### PR DESCRIPTION
**Pull request by bbb651**
Really liked the idea but couldn't stand the bright white background, so I decided to add dynamic dark mode support based on the system theme, as well as making the code shorter.
Good luck with your project! :)

### CODE REVIEW

**Comment by MichaelWehar** [comment]
An option for selecting the background color would be neat.  :)

**Comment by penge** [comment]
Nice work!

I am merging this.

**Comment by penge** [comment]
> An option for selecting the background color would be neat. :)

We may add Options mage for that! :)

We can have Options like:

- font type, font size
- color scheme

How about that??? :))

**Comment by penge** [comment]
> An option for selecting the background color would be neat. :)

We may add Options for that! :)

We may have Options like:

font type, font size
color scheme
How about that??? :))

**Comment by penge** [comment]
> An option for selecting the background color would be neat. :)

We may add Options for that! :)

We may have Options like:

- font type, font size
- color scheme

How about that??? :))

**Pull request merged**
